sudo: required

services:
  - docker

language: python

install:
  - docker --version
  - docker build -t maxking/mailman-core core/
  - docker build -t maxking/mailman-web web/
  - sudo pip install docker-compose
  - docker-compose --version

before_script:
  - docker-compose up -d
  - docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mailman-core
  - docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mailman-web
  - docker-compose ps
  - sleep 30

script:
   - tests/core.sh

after_script:
   - docker-compose down
